# Generated by Django 5.0.6 on 2025-01-21 18:49

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crush",
            name="created_at",
            field=pgcrypto.fields.EncryptedDateTimeField(
                blank=True,
                charset="utf-8",
                check_armor=True,
                cipher="aes",
                editable=False,
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name="crush",
            name="crush_email",
            field=pgcrypto.fields.EncryptedEmailField(
                charset="utf-8",
                check_armor=True,
                cipher="aes",
                help_text="The email of your crush",
                max_length=254,
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name="crush",
            name="crush_name",
            field=pgcrypto.fields.EncryptedCharField(
                charset="utf-8",
                check_armor=True,
                cipher="aes",
                help_text="The name of your crush",
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name="crush",
            name="message",
            field=pgcrypto.fields.EncryptedTextField(
                blank=True,
                charset="utf-8",
                check_armor=True,
                cipher="aes",
                help_text="Optional message for your crush",
                null=True,
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="matched_at",
            field=pgcrypto.fields.EncryptedDateTimeField(
                blank=True,
                charset="utf-8",
                check_armor=True,
                cipher="aes",
                editable=False,
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=pgcrypto.fields.EncryptedDateTimeField(
                blank=True,
                charset="utf-8",
                check_armor=True,
                cipher="aes",
                editable=False,
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=pgcrypto.fields.EncryptedCharField(
                charset="utf-8",
                check_armor=True,
                choices=[("submission", "Crush Submission"), ("match", "Match Found")],
                cipher="aes",
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="receiver_email",
            field=pgcrypto.fields.EncryptedEmailField(
                charset="utf-8",
                check_armor=True,
                cipher="aes",
                max_length=254,
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=pgcrypto.fields.EncryptedEmailField(
                charset="utf-8",
                check_armor=True,
                cipher="aes",
                max_length=254,
                primary_key=True,
                serialize=False,
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=pgcrypto.fields.EncryptedEmailField(
                charset="utf-8",
                check_armor=True,
                cipher="aes",
                max_length=150,
                versioned=False,
            ),
        ),
    ]
