# Generated by Django 5.0.6 on 2025-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_crush_created_at_alter_crush_crush_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crush",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="crush",
            name="crush_email",
            field=models.EmailField(
                help_text="The email of your crush", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="crush",
            name="crush_name",
            field=models.CharField(help_text="The name of your crush", max_length=50),
        ),
        migrations.AlterField(
            model_name="crush",
            name="message",
            field=models.TextField(
                blank=True, help_text="Optional message for your crush", null=True
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="matched_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("submission", "Crush Submission"), ("match", "Match Found")],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="receiver_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
